### PR TITLE
Added testcontainers dependency and configured simple coturn server

### LINKED ISSUE #2: Testing: Use local coturn via testcontainers instead of Google
The integration test currently uses a hardcoded stun server (stun.l.google.com, port 19302).
However this is not what we use at FAF. We use [coturn](https://github.com/coturn/coturn) running from a docker image.
The same could be achieved here, if we start if via [testcontainers](https://testcontainers.com/).

### PR DESCRIPTION
**Pull request by antonkosse**
Closes #2

### CODE REVIEW

**Comment by antonkosse** [comment]
Btw, the tests (and I believe the whole project) currently won't compile because of recent change to `UdpSocketBridge `- addition of `lobbyPort`, is it expected?
image

**Comment by Brutus5000** [comment]
I'll look into it.

**Comment by Brutus5000** [comment]
@antonkosse can you rebase and check if the tests pass?

**Review by Brutus5000 — APPROVED** [review]

**Comment by antonkosse** [comment]
And I've just decided to take a look into the status of PR  😅

**Pull request merged**
